<?php

require('fngssn.class.php');

// Instantiate the class
$fngssn = new fngssn();

// Generate a SSN for Florida 
echo $fngssn->generateSSN('FL');

echo '<br /><br />';

// Validate a SSN
echo $fngssn->validateSSN('421-61-1998');

?>
